### ISSUE TITLE
demo链接无效?

### ISSUE THREAD

**Issue by Running-z** [qq547276542/Agriculture_KnowledgeGraph#19]
你们项目里面提供的demo链接无法打开
![demo](https://user-images.githubusercontent.com/38971699/46060688-c3db8980-c196-11e8-911f-b636d9f898d6.png)

是否更新了链接,能否提供,实际体验下?

**Comment by qq547276542** [comment]
近期学校服务器在维护，暂时需要等一段时间

**Comment by qq547276542** [comment]
> 你们项目里面提供的demo链接无法打开
> ![demo](https://user-images.githubusercontent.com/38971699/46060688-c3db8980-c196-11e8-911f-b636d9f898d6.png)
> 
> 是否更新了链接,能否提供,实际体验下?

可以访问了
