### ISSUE TITLE
请教以下，本体构建是如何做的 ？  实体为什么要做分类 ? Keras在哪一块用到的？

### ISSUE THREAD

**Issue by FaerieLee** [qq547276542/Agriculture_KnowledgeGraph#33]

**Comment by OKtang** [comment]
同问本体构建部分相关内容

**Comment by qq547276542** [comment]
本体知识来源：https://www.wikidata.org/wiki/Wikidata:Main_Page      
树形结构来源：http://fenlei.baike.com/category/treeManage.jsp?cate=农业
实体分类是为农业实体识别，关系抽取，问答系统等功能服务的，同时也属于用户的需求
Keras是项目刚开始时的想法，后来弃用了，目前使用pytouch做关系抽取，正在开发中

**Comment by qq547276542** [comment]
我们没有使用本体数据库，使用的是neo4j存储的实体与关系（或者说我们没有从本体构建的角度来构建KG，而是直接把本体中的那些概念、关系保存在图结构中）。  因此没有owl文件，而是一系列的csv文件（见README）。

**Comment by FaerieLee** [comment]
非常感谢您的回复，学习到了很多
