### ISSUE TITLE
标记相关的几个问题

### ISSUE THREAD

**Issue by 1945083536** [qq547276542/Agriculture_KnowledgeGraph#35]
1、从代码看mongo有两个collection，一个是train_data，一个是test_data，前者在readme里说明了怎么准备，请问后者从哪里得到
2、我看修改tag只是写到txt里，而显示实体详情里，分类则是使用predict里的标签，那么这个修改如何奏效

请指教，谢谢

**Comment by CrisJk** [comment]
1. mongodb不是必要的，最初的设计是利用前端的标注工具从train_data中取一部分数据进行标注，作为test_data。test_data也可以直接从train_data中划出来

**Comment by 1945083536** [comment]
谢谢，我试了一下，只准备train_data，进行tagging，会自动将对应数据从train_data移到test_data
有个小问题，通常train指的是标记好的数据，test指的是未标记的数据，这里的命名让人觉得有点别扭。
