### ISSUE TITLE
wikidataAnalyse

### ISSUE THREAD

**Issue by qzhangliming** [qq547276542/Agriculture_KnowledgeGraph#36]
您好，wikidataSpider下没有wikidataAnalyse的目录，看介绍说attributes.csv是这个目录下的extractEntityAttribute.py得到的

**Comment by CrisJk** [comment]
@qzhangliming 
I have uploaded it just now.

**Comment by qzhangliming** [comment]
十分感谢。那是说目前项目中的数据都是爬虫爬取后放到neo4j数据库中，使用knn分类，然后demo可以直接使用吗？

**Comment by qzhangliming** [comment]
那么relation exaction得到的结果是在哪里进行使用的呢？

**Comment by qzhangliming** [comment]
目前代码没有看到使用这个结果的地方，是想要开发demo加上使用此模型对任意两个实体间的关系进行预测的功能吗？

**Comment by qzhangliming** [comment]
![default](https://user-images.githubusercontent.com/10335340/50472958-1296fa80-09f6-11e9-962b-faa2beb9ec2c.png)
请问项目的整体思路是这样的吗？想要自己走一遍，谢谢大神

**Comment by qzhangliming** [comment]
1.执行MyCrawler下的爬虫，获得hudong_pedia.json文件，需要转换为csv及导入到neo4j数据库。->2.使用了一个辅助训练集标注工具，得到predict_labels.txt。->3.运行wikidataSpider下的爬虫部分，得到相关数据->4.使用dfs_tree_crawler目录下的代码进行树形关系数据爬取。->5.运行relationExtraction目录下的相关代码进行关系提取，得到数据模型，目前这块结果demo中没有用到，可能是后期想要加上使用此模型对任意两个实体间的关系进行预测的功能。->6.使用KNN_PREDICT目录下的代码对数据进行清洗，及使用交叉验证(网格搜索)得到knn分类算法的的k值，然后对爬取的数据进行分类，一共有16类，是人为分的，有5000个已经手工标识好的数据作为训练集，将爬取的数据作为预测数据集进行分类，使用knn算法。->7.demo展示
请问大体流程是这样吗？想要自己跑一遍进行学习，谢谢大神。

**Comment by CrisJk** [comment]
@qzhangliming  
基本正确，由于网站改版的原因，一些爬虫代码可能不能用了，建议自己爬一下。wikidataSpider中有部分冗余代码和文件，该部分主要目的有4个：1、爬取得到wikidata_relation.csv和wikidata_relation2.csv ,得到知识库中的知识. 2、得到attribute.csv(实体的属性) 3、将知识库中的知识对齐到wikipedia上,得到关系提取数据集 4、得到城市气候等关系 。  可以有选择性的删减或增加自定义内容

**Comment by qzhangliming** [comment]
![default](https://user-images.githubusercontent.com/10335340/50473956-090f9180-09fa-11e9-9afc-2f464a028a69.png)
十分感谢，这是我最后整理的思路流程图。请问天气爬虫的部分能提供一下吗？在wikidataspider目录下没有找到。

**Comment by zihao-miao** [comment]
> ![default](https://user-images.githubusercontent.com/10335340/50473956-090f9180-09fa-11e9-9afc-2f464a028a69.png)
> 十分感谢，这是我最后整理的思路流程图。请问天气爬虫的部分能提供一下吗？在wikidataspider目录下没有找到。

你好关于关系标注的https://127.0.0.1:8000这个网站打不开，你是怎么解决的？能告诉我一下吗
