### ISSUE TITLE
Syntax error in try.py and 'unicode' was removed in Python 3

### ISSUE THREAD

**Issue by cclauss** [qq547276542/Agriculture_KnowledgeGraph#4]
flake8 testing of https://github.com/qq547276542/Agriculture_KnowledgeGraph on Python 3.6.3

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./demo/static/assets/jquery-file-upload/server/gae-python/main.py:70:38: F821 undefined name 'unicode'
            if type(fieldStorage) is unicode:
                                     ^
./wikidataSpider/wikidataCrawler/try.py:1:1: E999 SyntaxError: invalid syntax
<!DOCTYPE html>
^
1     E999 SyntaxError: invalid syntax
1     F821 undefined name 'unicode'
2
```

**Comment by CrisJk** [comment]
Thank you very much! This file is useless and we removed it.

**Comment by cclauss** [comment]
The '__unicode__' issue remains.

**Comment by qq547276542** [comment]
Now the problem is sloved . 
Because I use some opensource code of js and css, and without careful examination it. Now I delete these useless code.
Thanks for your help again 👍
