### ISSUE TITLE
成功搭建好8000端网站后，随意点击标签，比如“ADM公司“，出现如下网页反馈，请问一下该怎么解决？

### ISSUE THREAD

**Issue by miroft19960829** [qq547276542/Agriculture_KnowledgeGraph#48]
![捕获2](https://user-images.githubusercontent.com/46232653/55463909-92071c00-562c-11e9-8633-1cedf5897949.PNG)

**Comment by yingning** [comment]
请问你解决了这个问题吗？当我成功搭建好8000端网站后，我选择农知问答一栏，在输入问题的文本框中点击了热门搜索中推荐的问题，然后点击提交，出现了Server Error (500) 的情况，请问这是怎么回事？该如何处理，希望能够得到您的帮助答疑，谢谢！ @qq547276542

**Comment by yingning** [comment]
请问你解决了这个问题吗？当我成功搭建好8000端网站后，我选择农知问答一栏，在输入问题的文本框中点击了热门搜索中推荐的问题，然后点击提交，出现了Server Error (500) 的情况，请问这是怎么回事？该如何处理，希望能够得到您的帮助答疑，谢谢 @miroft19960829 @qq547276542
