### ISSUE TITLE
cypher语句有问题，导致报exception

### ISSUE THREAD

**Issue by ding00** [qq547276542/Agriculture_KnowledgeGraph#59]
按照流程走下来，在任意页面上，点击按钮，均报exception
![22_17_55__07_14_2019](https://user-images.githubusercontent.com/11608098/61184933-c192df00-a685-11e9-9113-ac1dae0abf7f.jpg)
![22_17_17__07_14_2019](https://user-images.githubusercontent.com/11608098/61184935-c5266600-a685-11e9-95a5-cc76eec35458.jpg)

debug发现，cypher语句进行查询时，导致了exception
请问是怎么回事呢？

**Comment by CrisJk** [comment]
@ding00  建议把调试窗口显示的Cypher语句放到Neo4j里执行看是否有问题？如果有问题是否是neo4j版本不对应导致的？

**Comment by ding00** [comment]
> @ding00 建议把调试窗口显示的Cypher语句放到Neo4j里执行看是否有问题？如果有问题是否是neo4j版本不对应导致的？

![23_31_57__07_14_2019](https://user-images.githubusercontent.com/11608098/61185788-c9f01780-a68f-11e9-85c8-c9d1dc29372d.jpg)
确实是报错的，请问你们用的neo4j的什么版本呢？

**Comment by CrisJk** [comment]
@ding00  neo4j以及其他环境版本号参见requirements.txt

**Comment by ding00** [comment]
> @ding00 neo4j以及其他环境版本号参见requirements.txt

检查过requirements中的各种环境版本，都是符合的，请帮忙看看，这个代码产生的cypher语句感觉有点不太对。长这样：MATCH (n:HudongItem { title: \\'小麦===\\' }) return n

**Comment by CrisJk** [comment]
@ding00  cypher语句变成这样， 应该是pycharm debugger的问题，我刚才试了一下，debugger的情况和你一样，但没有报错。
![image](https://user-images.githubusercontent.com/11531656/61193214-94c5e280-a6ec-11e9-9ba3-07996b308e05.png)

**Comment by ding00** [comment]
> @ding00 cypher语句变成这样， 应该是pycharm debugger的问题，我刚才试了一下，debugger的情况和你一样，但没有报错。
> ![image](https://user-images.githubusercontent.com/11531656/61193214-94c5e280-a6ec-11e9-9ba3-07996b308e05.png)

感谢，我可能是neo4j没有配置好导致的问题，和cypher语句无关，我重新配置了一番，就成功了，谢谢！还有一个问题，想问问你农知问答采用的什么算法？我看项目中的ppt没有介绍到这一部分。
