### ISSUE TITLE
demo前端无法显示关系图？（neo4j里可以正常显示）

### ISSUE THREAD

**Issue by niudd** [qq547276542/Agriculture_KnowledgeGraph#64]
如题，neo4j里可以正常显示关系图，但demo里却不显示？有没有人遇到过类似问题怎么解决
版本号：neo4j Desktop 1.2.1

![image](https://user-images.githubusercontent.com/7549570/67000840-1d4c8880-f10b-11e9-8483-0728c6ef69ad.png)

**Comment by xuwang0205** [comment]
same problem

**Comment by CrisJk** [comment]
可以看一下后端有没有报错吗？报的什么错？

**Comment by YYGe01** [comment]
> 可以看一下后端有没有报错吗？报的什么错？
谢谢，我的也是关系图显示不出来，后段没有报错，如下
[18/Oct/2019 13:10:42] "GET /search_entity?user_text=%E6%B0%B4%E7%A8%BB HTTP/1.1" 200 30724
[18/Oct/2019 13:13:37] "GET /search_entity?user_text=%E6%B0%B4%E7%A8%BB HTTP/1.1" 200 30724
[18/Oct/2019 13:14:13] "GET /search_entity?user_text=%E8%A2%81%E9%9A%86%E5%B9%B3 HTTP/1.1" 200 32612

**Comment by YYGe01** [comment]
> 可以看一下后端有没有报错吗？报的什么错？

不过刚开始启动的时候有黄色字体显示：
"GET /static/img/favicon.png HTTP/1.1" 404 1669

**Comment by YYGe01** [comment]
> 可以看一下后端有没有报错吗？报的什么错？
启动django会报红色错误，但是服务器可以启动。
You have 17 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.

**Comment by niudd** [comment]
> 可以看一下后端有没有报错吗？报的什么错？

![image](https://user-images.githubusercontent.com/7549570/67100383-22d0ce00-f1f2-11e9-9368-48866f0e424c.png)

![image](https://user-images.githubusercontent.com/7549570/67100442-3ed46f80-f1f2-11e9-8b1a-474ca2484b13.png)

![image](https://user-images.githubusercontent.com/7549570/67100479-514ea900-f1f2-11e9-8498-c4b070f2f841.png)

关系图区域里是空白。

**Comment by niudd** [comment]
启动项目的时候后段报了一句：

> You have 13 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.

**Comment by CrisJk** [comment]
感觉是echarts的锅，明天再看看

**Comment by YYGe01** [comment]
> > 可以看一下后端有没有报错吗？报的什么错？
> 
> 启动项目的时候后端报了一句：
> 
> > You have 13 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
> > Run 'python manage.py migrate' to apply them.

这个我解决了，你按上面的提示运行python3 manage.py migrate 就可以了，这个文件是demo文件夹里有的，但是没有解决关系图不显示的问题。

**Comment by CrisJk** [comment]
@niudd @xuwang0205 @YYGe01 
Fixed it! Please pull the latest version and enjoy it.
