### ISSUE TITLE
请教关于实体存储的方法

### ISSUE THREAD

**Issue by wangchuan2008888** [qq547276542/Agriculture_KnowledgeGraph#8]
最近认真拜读了这个项目,感觉很有学习意义和落地指导作用.
但是在看实体的信息的时候,注意到baseInfoKeyList和baseInfoValueList是用"##"分割的.
我所疑惑的是为什么不作为property存储?是出于项目需求还是一般惯例?
多谢分享这么优秀的项目.

**Comment by qq547276542** [comment]
主要是考虑 属性名和属性值的个数是不确定的。  当时认为用##分割后读取和处理不定长数组比较方便点
